#!/bin/bash


while getopts 'ha:d:g' OPTION; do
    case "$OPTION" in
        h)
            echo "usage: ecr-auth [-a AWS_CREDS] [-d DOCKER_CONFIG] [-g] [-h]"
            exit 0
            ;;

        a)
            aws_creds="$OPTARG"
            ;;
        d)
            docker_config="$OPTARG"
            ;;
        g)
            set_group=1
            ;;
        ?)
        echo "usage: ecr-auth [-a AWS_CREDS] [-d DOCKER_CONFIG] [-g] [-h]" >&2
        exit 1
        ;;
    esac
done
shift "$(($OPTIND -1))"


if [ ! -z "$aws_creds" ] && [ -f $aws_creds ]; then
    echo "sourcing $aws_creds"
    source $aws_creds
fi

if [ ! -z "$docker_config" ]; then
    export DOCKER_CONFIG="$docker_config"
fi

echo "attempting ECR authentication"
$(aws ecr get-login --no-include-email)

if [ "$?" -ne 0 ]; then
    exit $?
fi

if [ ! -z "$set_group" ] && [ ! -z "$docker_config" ]; then
    chmod g+r "${docker_config}/config.json"
fi

for service in `docker service ls --filter label=bangka.ecr-authenticator --format '{{.Name}}'`; do
    echo "updating $service"
    docker service update -d --with-registry-auth $service
done

exit 0
